### ISSUE TITLE
Impossible to install 

### ISSUE THREAD

**Issue by Hawzaz** [Kawatwist/Poke42#1]
When i clone the project, i try to make and it gives me these error :
```
find: ‘sources’: No such file or directory
SDL2 is installed.
make[1]: Entering directory '/home/tercio01/lomasse/libft'
ft_memmove.c: In function ‘ft_memmove’:
ft_memmove.c:19:7: error: variable ‘i’ set but not used [-Werror=unused-but-set-variable]
  int  i;
       ^
cc1: all warnings being treated as errors
Makefile:33: recipe for target 'ft_memmove.o' failed
make[1]: *** [ft_memmove.o] Error 1
make[1]: Leaving directory '/home/tercio01/lomasse/libft'
Makefile:81: recipe for target 'libft' failed
make: *** [libft] Error 2
```

Could you remove the compilation flags or adapt your code ?

My system is : WSL Ubuntu 18.04 LTS

**Comment by Kawatwist** [comment]
Sorry but we wont let the project's access to everyone actually, This is only a pre-beta version running only for us, the real project is on a private repository, we will tell you soon about the progression and if we could make a public version for you, Thanks
